// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using University.Persistance.Context;

#nullable disable

namespace University.Persistance.Migrations
{
    [DbContext(typeof(UniversityDbContext))]
    partial class UniversityDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("University.Domain.Entities.BaseEntities.Course", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CreadtedById")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("LastModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("LastModifiedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CreadtedById");

                    b.HasIndex("LastModifiedByUserId");

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("University.Domain.Entities.BaseEntities.CreditWork", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Code")
                        .HasColumnType("integer");

                    b.Property<Guid>("CreadtedById")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Heading")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("LastModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("LastModifiedByUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CreadtedById");

                    b.HasIndex("LastModifiedByUserId");

                    b.ToTable("CreditWorks");
                });

            modelBuilder.Entity("University.Domain.Entities.BaseEntities.Staff", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.HasKey("UserId");

                    b.ToTable("Staff");
                });

            modelBuilder.Entity("University.Domain.Entities.BaseEntities.Student", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CreadtedById")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("LastModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("LastModifiedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Roll")
                        .HasColumnType("integer");

                    b.HasKey("UserId");

                    b.HasIndex("CreadtedById");

                    b.HasIndex("LastModifiedByUserId");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("University.Domain.Entities.JunctionEntities.CourseCreditWork", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CreditWorkId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("CreditWorkId");

                    b.ToTable("CreditWorksInCourses");
                });

            modelBuilder.Entity("University.Domain.Entities.JunctionEntities.CourseEnrollment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CreadtedById")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("EnrolledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("LastModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("LastModifiedByUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("StaffId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("CreadtedById");

                    b.HasIndex("LastModifiedByUserId");

                    b.HasIndex("StaffId");

                    b.HasIndex("StudentId");

                    b.ToTable("CourseEnrollments");
                });

            modelBuilder.Entity("University.Domain.Entities.JunctionEntities.CreditWorkEnrollment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CreadtedById")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreditWorkId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("EnrolledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("LastModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("LastModifiedByUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("StaffId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CreadtedById");

                    b.HasIndex("CreditWorkId");

                    b.HasIndex("LastModifiedByUserId");

                    b.HasIndex("StaffId");

                    b.HasIndex("StudentId");

                    b.ToTable("CreditWorkEnrollments");
                });

            modelBuilder.Entity("University.Domain.Entities.BaseEntities.Course", b =>
                {
                    b.HasOne("University.Domain.Entities.BaseEntities.Staff", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreadtedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("University.Domain.Entities.BaseEntities.Staff", "LastModifiedBy")
                        .WithMany()
                        .HasForeignKey("LastModifiedByUserId");

                    b.Navigation("CreatedBy");

                    b.Navigation("LastModifiedBy");
                });

            modelBuilder.Entity("University.Domain.Entities.BaseEntities.CreditWork", b =>
                {
                    b.HasOne("University.Domain.Entities.BaseEntities.Staff", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreadtedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("University.Domain.Entities.BaseEntities.Staff", "LastModifiedBy")
                        .WithMany()
                        .HasForeignKey("LastModifiedByUserId");

                    b.Navigation("CreatedBy");

                    b.Navigation("LastModifiedBy");
                });

            modelBuilder.Entity("University.Domain.Entities.BaseEntities.Student", b =>
                {
                    b.HasOne("University.Domain.Entities.BaseEntities.Staff", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreadtedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("University.Domain.Entities.BaseEntities.Staff", "LastModifiedBy")
                        .WithMany()
                        .HasForeignKey("LastModifiedByUserId");

                    b.Navigation("CreatedBy");

                    b.Navigation("LastModifiedBy");
                });

            modelBuilder.Entity("University.Domain.Entities.JunctionEntities.CourseCreditWork", b =>
                {
                    b.HasOne("University.Domain.Entities.BaseEntities.Course", "Course")
                        .WithMany("CreditWorksInCourse")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("University.Domain.Entities.BaseEntities.CreditWork", "CreditWork")
                        .WithMany("CoursesOfCreditWork")
                        .HasForeignKey("CreditWorkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("CreditWork");
                });

            modelBuilder.Entity("University.Domain.Entities.JunctionEntities.CourseEnrollment", b =>
                {
                    b.HasOne("University.Domain.Entities.BaseEntities.Course", "Course")
                        .WithMany("StudentsInCourse")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("University.Domain.Entities.BaseEntities.Staff", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreadtedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("University.Domain.Entities.BaseEntities.Staff", "LastModifiedBy")
                        .WithMany()
                        .HasForeignKey("LastModifiedByUserId");

                    b.HasOne("University.Domain.Entities.BaseEntities.Staff", "EnrolledBy")
                        .WithMany()
                        .HasForeignKey("StaffId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("University.Domain.Entities.BaseEntities.Student", "Student")
                        .WithMany("CoursesEnrolled")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("CreatedBy");

                    b.Navigation("EnrolledBy");

                    b.Navigation("LastModifiedBy");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("University.Domain.Entities.JunctionEntities.CreditWorkEnrollment", b =>
                {
                    b.HasOne("University.Domain.Entities.BaseEntities.Staff", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreadtedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("University.Domain.Entities.BaseEntities.CreditWork", "CreditWork")
                        .WithMany("StudentsInCreditWork")
                        .HasForeignKey("CreditWorkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("University.Domain.Entities.BaseEntities.Staff", "LastModifiedBy")
                        .WithMany()
                        .HasForeignKey("LastModifiedByUserId");

                    b.HasOne("University.Domain.Entities.BaseEntities.Staff", "EnrolledBy")
                        .WithMany()
                        .HasForeignKey("StaffId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("University.Domain.Entities.BaseEntities.Student", "Student")
                        .WithMany("CreditWorksEnrolled")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedBy");

                    b.Navigation("CreditWork");

                    b.Navigation("EnrolledBy");

                    b.Navigation("LastModifiedBy");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("University.Domain.Entities.BaseEntities.Course", b =>
                {
                    b.Navigation("CreditWorksInCourse");

                    b.Navigation("StudentsInCourse");
                });

            modelBuilder.Entity("University.Domain.Entities.BaseEntities.CreditWork", b =>
                {
                    b.Navigation("CoursesOfCreditWork");

                    b.Navigation("StudentsInCreditWork");
                });

            modelBuilder.Entity("University.Domain.Entities.BaseEntities.Student", b =>
                {
                    b.Navigation("CoursesEnrolled");

                    b.Navigation("CreditWorksEnrolled");
                });
#pragma warning restore 612, 618
        }
    }
}
